baseURL = "https://jiekun.dev"
languageCode = "cn-zh"
defaultContentLanguage = "cn"
title = "Jiekun's Blog"
theme = "hermit"
# enableGitInfo = true
pygmentsCodefences  = true
pygmentsUseClasses  = true
# hasCJKLanguage = true  # If Chinese/Japanese/Korean is your main content language, enable this to make wordCount works right.
rssLimit = 10  # Maximum number of items in the RSS feed.
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License." # This message is only used by the RSS template.
enableEmoji = true  # Shorthand emojis in content files - https://gohugo.io/functions/emojify/
googleAnalytics = "G-Q11C6RN8VS"
# disqusShortname = "yourdiscussshortname"

[author]
  name = "杰坤"

[blackfriday]
  # hrefTargetBlank = true
  # noreferrerLinks = true
  # nofollowLinks = true

[taxonomies]
  tag = "tags"
  # Categories are disabled by default.

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"
  dateformMonth   = "Jan, 2006"

  # Metadata mostly used in document's head
  # description = ""
  # images = [""]
  themeColor = "#494f5c"

  homeSubtitle = "A developer."
  footerCopyright = ' &#183; <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
  # bgImg = ""  # Homepage background-image URL

  # Prefix of link to the git commit detail page. GitInfo must be enabled.
  # gitUrl = "https://github.com/2014bduck"

  # Toggling this option needs to rebuild SCSS, requires Hugo extended version
  justifyContent = false  # Set "text-align: justify" to `.content`.

  relatedPosts = false  # Add a related content section to all single posts page

  code_copy_button = true # Turn on/off the code-copy-button for code-fields
  
  # Add custom css
  customCSS = ["assets/custom.css"]

  # Social Icons
  # Check https://github.com/Track3/hermit#social-icons for more info.
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/ReadTheDuck"

  #[[params.social]]
  #  name = "instagram"
  #  url = "https://instagram.com/"

  [[params.social]]
    name = "github"
    url = "https://github.com/2014bduck"

  [[params.social]]
    name = "email"
    url = "mailto:jiekun.dev@gmail.com"

  [[params.social]]
    name = "qq"
    url = "http://wpa.qq.com/msgrd?v=3&uin=136986560&site=qq&menu=yes"
  
  [[params.social]]
    name = "wechat"
    url = "https://camo.githubusercontent.com/0dd9edc3b23f8b61337c708ef9882c8e25c1a0935532d8ebaed3e6ff937e70a5/68747470733a2f2f707470696d672e6d652f7838363637762e706e67"

  [[params.social]]
    name = "friends"
    url = "friends/"

[menu]

  [[menu.main]]
    name = "Posts"
    url = "posts/"
    weight = 10

  [[menu.main]]
    name = "About Me"
    url = "about-me/"
    weight = 20

  [[menu.main]]
    name = "Schedule"
    url = "https://trello.com/b/7Yru9uvH"
    weight = 30